# Generated by Django 4.1.5 on 2023-02-01 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919198989'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('role', models.CharField(choices=[('customer', 'customer'), ('nazer', 'nazer'), ('operator', 'operator'), ('admin', 'admin')], max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user', verbose_name='customer_id')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='products.products', verbose_name='product_id')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('avenue_name', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=3)),
                ('zipCode', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='users.user', verbose_name='customer_id')),
            ],
        ),
    ]
