# Generated by Django 4.1.5 on 2023-02-01 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountKind', models.CharField(choices=[('daily', 'daily'), ('birthDay', 'BirthDay'), ('cash', 'cash')], max_length=15)),
                ('persent', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('superCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superCategory_id', to='products.supercategory', verbose_name='superCategory_id')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=10)),
                ('productInventory', models.CharField(choices=[('Available', 'Available'), ('finished', 'finished')], max_length=15)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_id', to='products.discount', verbose_name='discount_id')),
                ('subCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCategory_id', to='products.supercategory', verbose_name='subCategory_id')),
            ],
            options={
                'verbose_name': 'کاربران',
            },
        ),
    ]
