# Generated by Django 4.1.5 on 2023-02-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'products'},
        ),
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='subCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCategory_id', to='products.subcategory', verbose_name='subCategory_id'),
        ),
    ]
